version: '3'
services:
  app:
    build: .
    env_file: .env
    ports:
     - 3000:3000
    depends_on:
     - db
    volumes:
    - ./:/app
    - ./nodemon.json:/app/src/nodemon.json
    - '/app/node_modules'
    command: npm run dev

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  postgres-data:
